version: '3.8'

services:
  db:
    image: postgres:15
    container_name: proton_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sistemas_secret_password
      POSTGRES_DB: proton_vault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: